TTTTTTTTTTTTTTTTTTTTT
T--------T--T-------T
T--------T--T-------T
T--------T--T-------T
T-------------------T
T--------T--T-------T
T--------T--T-------T
T--------T--T-------T
T--------T--T-------T
TTTTTTTTTT--TTTTTTTTT
T--------T--T-------T
T--------T--T-------T
T--------T--T-------T
T-------------------T
T--------T--T-------T
T--------T--T-------T
T--------T--T-------T
TTTTTTTTTT--TTTTTTTTT
T--------T--T-------T
T--------T--T-------T
T--------T--T-------T
T-------------------T
T--------T--T-------T
T--------T--T-------T
T--------T--T-------T
T--------T--T-------T
TTTTTTTTTT--TTTTTTTTT
T--------T--T-------T
T--------T--T-------T
T--------T--T-------T
T-------------------T
T--------T--T-------T
T--------T--T-------T
T--------T--T-------T
TTTTTTTTTT--TTTTTTTTT
T-------------------T
T-------------------T
T----------------TTTT
T----------------TTTT
TTTTTTTTTTTTTTTTTTTTT

TTTTTTTTTTTTTTTTTTTTT
T--------T--T-------T
T--------T--T-------T
G--------T--T-------G
G-------------------G
G--------T--T-------G
T--------T--T-------T
T--------T--T-------T
T--------T--T-------T
TTTTTTTTTT--TTTTTTTTT
T--------T--T-------T
T--------T--T-------T
G--------T--T-------G
G-------------------G
G--------T--T-------G
T--------T--T-------T
T--------T--T-------T
TTTTTTTTTT--TTTTTTTTT
T--------T--T-------T
T--------T--T-------T
G--------T--T-------G
G-------------------G
G--------T--T-------G
T--------T--T-------T
T--------T--T-------T
T--------T--T-------T
TTTTTTTTTT--TTTTTTTTT
T--------T--T-------T
T--------T--T-------T
G--------T--T-------G
G-------------------G
G--------T--T-------G
T--------T--T-------T
T--------T--T-------T
TTTTTTTTTT--TTTTTTTTT
T-------------------T
G-------------------G
G---------------T---G
G---------------T---G
TTTTTTTTTTTTTTTTTTTTT

TTTTTTTTTTTTTTTTTTTTT
T--------T--T-------T
T--------T--T-------T
G--------T--T-------G
G-------------------G
G--------T--T-------G
T--------T--T-------T
T--------T--T-------T
T--------T--T-------T
TTTTTTTTTT--TTTTTTTTT
T--------T--T-------T
T--------T--T-------T
G--------T--T-------G
G-------------------G
G--------T--T-------G
T--------T--T-------T
T--------T--T-------T
TTTTTTTTTT--TTTTTTTTT
T--------T--T-------T
T--------T--T-------T
G--------T--T-------G
G-------------------G
G--------T--T-------G
T--------T--T-------T
T--------T--T-------T
T--------T--T-------T
TTTTTTTTTT--TTTTTTTTT
T--------T--T-------T
T--------T--T-------T
G--------T--T-------G
G-------------------G
G--------T--T-------G
T--------T--T-------T
T--------T--T-------T
TTTTTTTTTT--TTTTTTTTT
T-------------------T
G-------------------G
G--------------T----G
G--------------T----G
TTTTTTTTTTTTTTTTTTTTT

TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTTTTTTTT
TTTTTTTTTTTTTTT-----T
TTTTTTTTTTTTTTT-----T
TTTTTTTTTTTTTTTTTTTTT
